[tox]
# Test on the following Python versions
envlist = py313

toxworkdir=../builds/flaskdash/tox
skipsdist=True

[testenv]
deps = -r{toxinidir}/requirements.txt

# Run automated test suite
commands=
    pytest tests/
